name: Build APK

on:
  push:
    branches:
      - main  # Set your main branch name here
  pull_request:
    branches:
      - main  # Set your main branch name here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'  # Set your Flutter version here

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        tag: ${{ github.event.inputs.release_version }}
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
